version: '3.8'

services:
    postgres:
        image: postgres:15 # Pode especificar a versão do Postgres que desejar
        container_name: meu_projeto_postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
            POSTGRES_DB: ${DB_DATABASE:-blog_laravel}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-blog_laravel}"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
        driver: local
