<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;

// Home page
Route::get('/', function () {
    return redirect()->route('posts.index');
});

// Authentication routes (Generated by Laravel/UI)
Auth::routes();

// Post routes
// Public routes (index, show)
Route::resource('posts', PostController::class)->only(['index', 'show']);
Route::get('/posts/{post}', [PostController::class, 'show'])->name('posts.show');
// Ruthes that require authentication (crete, store, edit, update, destroy)
Route::resource('posts', PostController::class)->except(['index', 'show'])->middleware('auth');

// Comment routes (nested and protected by authentication)
Route::resource('posts.comments', CommentController::class)
    ->only(['store', 'destroy'])
    ->middleware('auth');

//Home route
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
