<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;

// Home page
Route::get('/', function () {
    return redirect()->route('posts.index');
});

// Authentication routes (Generated by Laravel/UI)
Auth::routes();

// Public routes for posts
Route::get('/posts', [PostController::class, 'index'])->name('posts.index');
Route::get('/posts/{post}', [PostController::class, 'show'])->name('posts.show');

// Routes that require authentication
Route::middleware(['auth'])->group(function () {
    // Create new post
    Route::get('/posts/create', [PostController::class, 'create'])->name('posts.create');
    Route::post('/posts', [PostController::class, 'store'])->name('posts.store');
    // Edit existing post
    Route::get('/posts/{post}/edit', [PostController::class, 'edit'])->name('posts.edit');
    Route::put('/posts/{post}', [PostController::class, 'update'])->name('posts.update');
    // Delete post
    Route::delete('/posts/{post}', [PostController::class, 'destroy'])->name('posts.destroy');
});

// Create all RESTful routes for the PostController
Route::resource('posts', PostController::class);

// Create Comment routes neasted under posts
Route::resource('posts.comments', CommentController::class)->only([
    'store', 'destroy'
]);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
